apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: react-fastapi-app
  description: React + FastAPI + SQLite demo service
spec:
  type: service
  owner: user:github/sairamreddy77
  lifecycle: experimental
  providesApis:
    - react-fastapi-api


---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: react-fastapi-api
spec:
  type: openapi
  lifecycle: experimental
  owner: user:github/sairamreddy77
  definition:
    $text: ./openapi.json

    # $openapi: http://localhost:8000/openapi.json
    # $text: |
    #   openapi: 3.0.0
    #   info:
    #     title: Simple API
    #     version: 1.0.0
    #   paths:
    #     /health:
    #       get:
    #         summary: Health check
    #         responses:
    #           '200':
    #             description: OK

